Reload weights after plateau
mozilla/STT pull request #3245
Opened 2020-08-12 14:52 UTC by DanBmh

Reload checkpoint weights after reaching a plateau that we use the best_dev weights again

2020-08-13 00:08 UTC, lissyx commented
@DanBmh Thanks, can you elaborate a little bit? My mind is kind of somewhere else, so I'm unsure I get the point here.

2020-08-13 08:20 UTC, DanBmh commented
Currently training looks like this:
```
epoch 5: val_loss=62
e6: vl=59
e7: vl=60
e8: vl=61
Reached a plateau, LearningRate:=LR*0.1
e9: vl=60       <- Here we're using the weights from e8, with the suggested changes we're using e6 instead
e10: vl=58   <- We have an improvement but the network has to do some more work to fix the errors from e7+e8
```

The old approach did still work well but I think we can make it even better by reloading the weights from the best_dev checkpoint.

2020-08-14 08:27 UTC, DanBmh commented
Not ready yet! 
Found an error when using `--drop_source_layers` flag

2020-08-14 09:13 UTC, DanBmh commented
Working again:)

2020-08-19 12:56 UTC, reuben requested changes

2020-08-19 12:56 UTC, reuben commented on training/mozilla_voice_stt_training/train.py
> +                        load_or_init_graph_for_training(session, allow_drop_layers=False)
Please keep this function unchanged and add a new explicitly `load_best_checkpoint` function, we don't want this call to load last silently for example.

2020-08-19 15:18 UTC, reuben approved these changes

2020-08-19 15:25 UTC, reuben commented
Re-opened as #3261 to run tests.

2020-08-20 07:48 UTC, reuben commented
Merged in #3261

2020-08-20 07:48 UTC, closed without merging